services:
  db:
    image: mysql:8.0
    container_name: rupeewise-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rupeewise
      MYSQL_DATABASE: rupeewise
    ports:
      - "3307:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - rupeewise_db:/var/lib/mysql
    command: [ "--default-authentication-plugin=mysql_native_password" ]

  app:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: rupeewise-app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rupeewise
      DB_NAME: rupeewise
      DB_PORT: 3306
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_MODEL: ${GEMINI_MODEL}
      FILE_STORAGE_PROVIDER: ${FILE_STORAGE_PROVIDER:-local}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_PUBLIC_BASE_URL: ${AWS_S3_PUBLIC_BASE_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-465}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}

    ports:
      - "3000:3000"
    volumes:
      - ./bills:/app/bills

volumes:
  rupeewise_db:
